# Generated by Django 4.0.3 on 2022-03-30 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='datecenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('provider_name', models.CharField(max_length=100)),
                ('lng', models.FloatField(max_length=100)),
                ('lat', models.FloatField(max_length=100)),
            ],
        ),
    ]
